
// -----------------  JavaScript Language File --------------

// -----------------  System Text Entries in Default Language --------------
// _LLS-textes are used in JavaScript functions, translations further below.


var _LLS={
"load":       "Loading data...",
"login":      "Login",
"un":         "Username",
"pwd":        "Password",
"welcome":	  "Welcome",
"save-ok":    "Ok, stored",
"invalid":    "Invalid changes!",
"unsaved":    "Unsaved Changes!",
"check":      "Please check the field",
"rows":       "Rows",
"data-no":    "No data",
"reload":     "Ok, reloading in a second",
"offline":    "We are offline! Trying to reconnect...",
"online":     "Nice, we are online again!",
"down":       "The server is down! Please try again later.",
"conn-err":   "Too many connection errors. Please login again.",
"choose-opt": "Choose",
"choose-row": "Please choose a row in the table!",
"perm-no":    "Not sufficient rights available.",
"q-del":	  "Do you really want to delete?",
"goodbye":    "Have a good day!",
"login-title":"Login",
"login-un":   "Username",
"login-pwd":  "Password",
"login-but":  "Ok, login",
"login-auto": "Remember me",
"login-err":  "Login Error. Please try again.",
"yes":        "Yes",
"no":         "No",
"readmore":   "Read more...",
"readless":   "less",
"ux-delete":  "Reset Client-Settings*",
"ux-delete-help": "Non-critical browser-settings like table-sorting or visual preferences.",
"ux-setting": "Settings",
"thanks":      "Thank You!",
// --------- time
"sec":        "s",
"sec1":       "Second",
"secn":       "Seconds",  
"min":        "min",
"min1":       "Minute",
"minn":       "Minutes",  
"h":          "H",
"h1":         "Hour",
"hn":         "Hours",  
"day":        "d",
"day1":       "Day",
"dayn":       "Days",
"w":          "W",
"w1":         "Week",
"wn":         "Weeks",
"mon":        "Mon.",
"mon1":       "Month",
"monn":       "Month",
"y":          "Y",
"y1":         "Year",
"yn":         "Years",
"jan":        "Jan.",
"feb":        "Feb.",
"mar":        "Mar.",
"apr":        "Apr.",
"may":        "May",
"jun":        "June",
"jul":        "July",
"aug":        "Aug.",
"sep":        "Sep.",
"oct":        "Oct.",
"nov":        "Nov.",
"dec":        "Dec."
};
    
// ---------------------------------------------------------------------------
// Translation from default language ('en') to German ('de')
var _LLD = {};   
_LLD.de=
{
"Loading data...":                      "Lade Daten...",
"Login":                                "Login",
"Username":                             "Benutzername",
"Password":                             "Kennwort",
"Welcome":                              "Willkommen",
"Ok, stored":                           "Ok, gespeichert",
"Invalid changes!":                     "Ungültige Änderungen!",
"Unsaved Changes!":                     "Ungespeicherte Änderungen!",
"Please check the field":               "Bitte dieses Feld prüfen:",
"Rows":                                 "Zeilen",
"No data":                              "Keine Daten",
"Ok, reloading in a second":            "Ok, Neuladen in einer Sekunde",
"We are offline! Trying to reconnect...": "Wir sind offline! Versuche zu verbinden...",
"Nice, we are online again!":           "Ok, wir sind wieder online!",
"The server is down! Please try again later.": "Der Server ist offline. Bitte später nochmal probieren.",
"Too many connection errors. Please login again.": "Zu viele Verbindungsfehler. Bitte neu anmelden.",
"Choose":                               "Auswahl",
"Please choose a row in the table!":    "Bitte eine Zeile in der Tabelle auswählen!",
"Not sufficient rights available.":      "Nicht genügend Rechte vorhanden.",
"Do you really want to delete?":        "Wollen Sie wirklich löschen?",
"Have a good day!":                     "Einen guten Tag noch!",
"Login":                                "Anmelden",
"Ok, login":                            "Ok, login",
"Username":                             "Benutzer",
"Password":                             "Kennwort",
"Remember me":                          "Angemeldet bleiben",
"Login Error. Please try again.":       "Login Fehler. Bitte nochmal probieren..",
"Yes":                                  "Ja",
"No":                                   "Nein",
"Read more...":                         "Mehr...",
"less":                                 "weniger",
"Reset Client-Settings*":              "Voreinstellungen* löschen",
"Non-critical browser-settings like table-sorting or visual preferences.": "Damit gemeint sind unbedenkliche Dinge wie Tabellen-Sortierung und diverse Anzeige-Optionen.",
"Settings":                             "Einstellungen",
"Thank You!":                           "Vielen Dank!",
// --------- time ----------
"s":          "s",
"Second":     "Sekunde",
"Seconds":    "Sekunden",  
"min":        "min",
"Minute":     "Minute",
"Minutes":    "Minuten",  
"H":          "H",
"Hour":       "Stunde",
"Hours":      "Stunden",  
"d":          "T",
"Day":        "Tag",
"Days":       "Tage",
"W":          "W",
"Week":       "Woche",
"Weeks":      "Wochen",
"Mon.":       "Mon.",
"Month":      "Monat",
"Month":      "Monate",
"Y":          "J",
"Year":       "Jahr",
"Years":      "Jahre",
"Jan.":       "Jan.",
"Feb.":       "Feb.",
"Mar.":       "Mär.",
"Apr.":       "Apr.",
"May":        "Mai",
"June":       "Juni",
"July":       "Juli",
"Aug.":       "Aug.",
"Sep.":       "Sep.",
"Oct.":       "Okt.",
"Nov.":       "Nov.",
"Dec.":       "Dez.",
// ---------------- settings -----------
"Language":                       "Sprache",
"Timezone":                       "Zeitzone",
"Look & Feel":                    "Aussehen & Verhalten",
"Font Size":                      "Schriftgröße",
"Zoom":                           "Zoom",
"Theme":                          "Theme",
"Effect":                         "Effekt",
"None":                           "Kein",
"Hide Main Menu":                 "Hauptmenu ausblenden",
"Fullscreen Mode":                "Vollbild-Modus",
"Invert Screen":                  "Invertierte Farben",
"Sepia Effect":                   "Sepia-Effekt",
"General Settings":               "Allgemeines",
"Reset Client-Settings*":         "Einstellungen* zurücksetzen",
"* Non-critical browser-settings like table-sorting or visual preferences.": "* Damit gemeint sind unbedenkliche Dinge wie 'Tabellen-Sortierung' und diverse Anzeige-Optionen.",
// -------------------------- contact from ------------------------------------
"Subject":                        "Betreff",
"Topic":                          "Thematik",
"Your message":                   "Ihre Nachricht",
"Send":                           "Absenden",
"Other":                          "Keine Auswahl",
"Request":                        "Anfrage",
"Question":                       "Frage",
"Feedback":                       "Kritik/Lob",
"Bug-Report":                     "Fehlerbericht",
"Legal matter":                   "Legales",
};

    
// ---------------------------------------------------------------------------
// Translation from default language ('en') to Spanish ('es')
_LLD.es=
{
"Loading data...":                      "Cargando…",
"Login":                                "Login",
"Username":                             "Usuario",
"Password":                             "Contraseña",
"Welcome":                              "Bienvenidas",
"Ok, stored":                           "Ok, guardada",
"Invalid changes!":                     "Cambios inválidos!",
"Unsaved Changes!":                     "Cambios sin guardar!",
"Please check the field":               "Por favor revise:",
"Rows":                                 "Filas",
"No data":                              "Sin data",
"Ok, reloading in a second":            "Ok, recarga en un segundo...",
"We are offline! Trying to reconnect...": "Estamos fuera de linea! Intentando reconectar...",
"Nice, we are online again!":           "Estamos en línea nuevamente!",
"The server is down! Please try again later.": "El servidor está caído! Por favor reinícielo.",
"Too many connection errors. Please login again.": "Demasiados errores de conexión. Por favor inicie sesión nuevamente.",
"Choose":                               "Elige una opcion",
"Please choose a row in the table!":    "Por favor, elija una fila en la tabla!",
"Not sufficient rights available.":      "No hay suficientes derechos disponibles.",
"Do you really want to delete?":        "¿Realmente quieres eliminar estos datos?",
"Have a good day!":                     "Hasta luego!",
"Login":                                "Login",
"Username":                             "Usuario",
"Password":                             "Contraseña",
"Ok, login":                            "Ok, login",
"Remember me":                          "Permanecer registrado",
"Login Error. Please try again.":       "Error de inicio de sesión. Inténtalo de nuevo.",
"Yes":                                  "Si",
"No":                                   "No",
"Read more...":                         "Leer más...",
"less":                                 "menos",
"Reset Client-Settings*":              "Eliminar configuración del cliente*",
"Non-critical browser-settings like table-sorting or visual preferences.": "Configuración del navegador no crítica como clasificación de tablas o preferencias visuales.",
"Settings":                             "Ajustes",
"Thank You!":                           "¡Gracias!",
// --------- time ----------
"s":          "s",
"Second":     "Secundo",
"Seconds":    "Secundos",  
"min":        "min",
"Minute":     "Minuto",
"Minutes":    "Minutos",  
"H":          "H",
"Hour":       "Hora",
"Hours":      "Horas",  
"d":          "D",
"Day":        "Dia",
"Days":       "Dias",
"W":          "Sem.",
"Week":       "Semana",
"Weeks":      "Semanas",
"Mon.":       "Mes.",
"Month":      "Mes",
"Month":      "Meses",
"Y":          "A",
"Year":       "Año",
"Years":      "Años",
"Jan.":       "Jan.",
"Feb.":       "Feb.",
"Mar.":       "Mar.",
"Apr.":       "Ápr.",
"May":        "Mayo",
"June":       "Jun.",
"July":       "Jul.",
"Aug.":       "Ag.",
"Sep.":       "Sep.",
"Oct.":       "Oct.",
"Nov.":       "Nov.",
"Dec.":       "Dec.",
// ---------------- settings -----------
"Language":                       "Idioma",
"Timezone":                       "Zona horaria",
"Look & Feel":                    "Apariencia",
"Font Size":                      "Fuente",
"Zoom":                           "Zoom",
"Theme":                          "Theme",
"Effect":                         "Efecto",
"None":                           "Sin",
"Hide Main Menu":                 "Ocultar Menú",
"Fullscreen Mode":                "Pantalla Completa",
"Invert Screen":                  "Invertir pantalla",
"Sepia Effect":                   "Efecto sepia",
"General Settings":               "Configuración general",
"Reset Client-Settings*":         "Resetar configuración del cliente*",
"* Non-critical browser-settings like table-sorting or visual preferences.": "* Configuración del navegador no crítica como clasificación de tablas o preferencias visuales.",
// -------------------------- contact from ------------------------------------
"Subject":                        "Asunto",
"Topic":                          "Tema",
"Your message":                   "Su mensaje",
"Send":                           "Envía",
"Other":                          "Otro",
"Request":                        "Solicite",
"Question":                       "Pregunta",
"Feedback":                       "Feedback",
"Bug-Report":                     "Bug-Report",
"Legal matter":                   "Legal",
};




//----------------------------------------------------


//-------------------------
function LLS(k)  // for system texts
{
    if(k in _LLS) return LL(_LLS[k]);
    console.warn("LLS-Language-Fallback! Key: " + k);
    return LL(k); // Fallback
}

//-------------------------
function LL(s) // for texts from default-language to current language
{
    if(typeof _LLD[_lang] == UN) return s;
    if(s in _LLD[_lang]) return _LLD[_lang][s];
    console.warn("Language-Fallback! Key: " + s);
    return s;  
}



